# Generated by Django 3.1.13 on 2021-09-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='place_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Identification of Place'),
        ),
    ]
